/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isis.ups.edu.Presentacion;

import CLIPSJNI.Environment;
import CLIPSJNI.PrimitiveValue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Antony
 */
public class PanelTest extends javax.swing.JPanel {

    /**
     * Variables
     */
    private Environment clips;
    public int Valorpregunta1, Valorpregunta2, Valorpregunta3, Valorpregunta4,
            Valorpregunta5, Valorpregunta6, Valorpregunta7, Valorpregunta8, Valorpregunta9, Valorpregunta10,
            Valorpregunta11, Valorpregunta12, Valorpregunta13, Valorpregunta14, Valorpregunta15, Valorpregunta16, Valorpregunta17, Valorpregunta18;

    /**
     * Creates new form PanelTest
     */
    public PanelTest() {
        initComponents();
        clips = new Environment();
        clips.load("ReglasMotricidad.clp");
        clips.reset();
        clips.run();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnRealizarTest = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnOpcion1Pregunta4 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta4 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        btnOpcion1Pregunta6 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta6 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnOpcion1Pregunta1 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnOpcion1Pregunta3 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta3 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnOpcion1Pregunta2 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnOpcion1Pregunta5 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta5 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        btnOpcion1Pregunta10 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta10 = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        btnOpcion1Pregunta8 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta8 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        btnOpcion1Pregunta7 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta7 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        btnOpcion1Pregunta9 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta9 = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        btnOpcion1Pregunta12 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta12 = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        btnOpcion1Pregunta13 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta13 = new javax.swing.JRadioButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        btnOpcion1Pregunta14 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta14 = new javax.swing.JRadioButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        btnOpcion1Pregunta17 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta17 = new javax.swing.JRadioButton();
        jLabel62 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        btnOpcion1Pregunta18 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta18 = new javax.swing.JRadioButton();
        jLabel64 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        btnOpcion1Pregunta11 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta11 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        btnOpcion1Pregunta15 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta15 = new javax.swing.JRadioButton();
        jLabel52 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        btnOpcion1Pregunta16 = new javax.swing.JRadioButton();
        btnOpcion2Pregunta16 = new javax.swing.JRadioButton();
        jLabel60 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isis/ups/Imagenes/atras.png"))); // NOI18N
        jButton1.setText("Salir");

        btnRealizarTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isis/ups/Imagenes/adelante.png"))); // NOI18N
        btnRealizarTest.setText("Adelante");
        btnRealizarTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarTest, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btnRealizarTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isis/ups/Imagenes/paciente.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel22.setText("NO");
        jPanel7.add(jLabel22);
        jPanel7.add(btnOpcion1Pregunta4);
        jPanel7.add(btnOpcion2Pregunta4);

        jLabel24.setText("SI");
        jPanel7.add(jLabel24);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel28.setText("NO");
        jPanel8.add(jLabel28);
        jPanel8.add(btnOpcion1Pregunta6);
        jPanel8.add(btnOpcion2Pregunta6);

        jLabel27.setText("SI");
        jPanel8.add(jLabel27);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel19.setText("NO");
        jPanel3.add(jLabel19);
        jPanel3.add(btnOpcion1Pregunta1);
        jPanel3.add(btnOpcion2Pregunta1);

        jLabel23.setText("SI");
        jPanel3.add(jLabel23);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("                     ¿Logra equilibrarse sobre una pierna?");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel20.setText("NO");
        jPanel4.add(jLabel20);
        jPanel4.add(btnOpcion1Pregunta3);
        jPanel4.add(btnOpcion2Pregunta3);

        jLabel26.setText("SI");
        jPanel4.add(jLabel26);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel18.setText("NO");
        jPanel6.add(jLabel18);
        jPanel6.add(btnOpcion1Pregunta2);
        jPanel6.add(btnOpcion2Pregunta2);

        jLabel17.setText("SI");
        jPanel6.add(jLabel17);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel21.setText("NO");
        jPanel11.add(jLabel21);
        jPanel11.add(btnOpcion1Pregunta5);
        jPanel11.add(btnOpcion2Pregunta5);

        jLabel25.setText("SI");
        jPanel11.add(jLabel25);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("                           ¿Puede levantar los brazos?");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("                      ¿Puede realizar giros con las muñecas?");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("                             ¿Puede doblar las piernas?");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("                               ¿Puede estirar las piernas?");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("                                     ¿Puede pestañear?");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel40.setText("NO");
        jPanel5.add(jLabel40);
        jPanel5.add(btnOpcion1Pregunta10);
        jPanel5.add(btnOpcion2Pregunta10);

        jLabel39.setText("SI");
        jPanel5.add(jLabel39);

        jPanel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel34.setText("NO");
        jPanel16.add(jLabel34);
        jPanel16.add(btnOpcion1Pregunta8);
        jPanel16.add(btnOpcion2Pregunta8);

        jLabel33.setText("SI");
        jPanel16.add(jLabel33);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel31.setText("NO");
        jPanel10.add(jLabel31);
        jPanel10.add(btnOpcion1Pregunta7);
        jPanel10.add(btnOpcion2Pregunta7);

        jLabel30.setText("SI");
        jPanel10.add(jLabel30);

        jPanel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel37.setText("NO");
        jPanel17.add(jLabel37);
        jPanel17.add(btnOpcion1Pregunta9);
        jPanel17.add(btnOpcion2Pregunta9);

        jLabel36.setText("SI");
        jPanel17.add(jLabel36);

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("                     ¿Puede mover objetos hacia adelante?");
        jLabel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("                        ¿Puede mover objetos hacia atrás?");
        jLabel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("                      ¿Puede mover objetos hacia arriba?");
        jLabel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel38.setBackground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("                              ¿Puede mover objetos hacia abajo?");
        jLabel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel43.setText("NO");
        jPanel12.add(jLabel43);
        jPanel12.add(btnOpcion1Pregunta12);
        jPanel12.add(btnOpcion2Pregunta12);

        jLabel44.setText("SI");
        jPanel12.add(jLabel44);

        jLabel45.setBackground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("           ¿Puede realizar movimientos combinados ojo mano?");
        jLabel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel46.setBackground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("                     ¿Tiene agilidad en los movimientos?");
        jLabel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel47.setText("NO");
        jPanel13.add(jLabel47);
        jPanel13.add(btnOpcion1Pregunta13);
        jPanel13.add(btnOpcion2Pregunta13);

        jLabel48.setText("SI");
        jPanel13.add(jLabel48);

        jPanel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel49.setText("NO");
        jPanel14.add(jLabel49);
        jPanel14.add(btnOpcion1Pregunta14);
        jPanel14.add(btnOpcion2Pregunta14);

        jLabel50.setText("SI");
        jPanel14.add(jLabel50);

        jLabel53.setBackground(new java.awt.Color(204, 204, 204));
        jLabel53.setText("                         ¿Puede realizar saltos con dos piernas?");
        jLabel53.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel54.setBackground(new java.awt.Color(204, 204, 204));
        jLabel54.setText("                        ¿Puede realizar saltos con una pierna?");
        jLabel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel55.setBackground(new java.awt.Color(204, 204, 204));
        jLabel55.setText("             ¿Puede realizar movimientos combinados pierna brazo?");
        jLabel55.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel56.setBackground(new java.awt.Color(204, 204, 204));
        jLabel56.setText("            ¿Tiene velocidad en la reacción de los movimientos?");
        jLabel56.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel57.setBackground(new java.awt.Color(204, 204, 204));
        jLabel57.setText("                                                 ¿  ?");
        jLabel57.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setText("                               ¿Tiene control viso motora?");
        jLabel58.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel61.setText("NO");
        jPanel19.add(jLabel61);
        jPanel19.add(btnOpcion1Pregunta17);
        jPanel19.add(btnOpcion2Pregunta17);

        jLabel62.setText("SI");
        jPanel19.add(jLabel62);

        jPanel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel63.setText("NO");
        jPanel20.add(jLabel63);
        jPanel20.add(btnOpcion1Pregunta18);
        jPanel20.add(btnOpcion2Pregunta18);

        jLabel64.setText("SI");
        jPanel20.add(jLabel64);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel41.setText("NO");
        jPanel9.add(jLabel41);
        jPanel9.add(btnOpcion1Pregunta11);
        jPanel9.add(btnOpcion2Pregunta11);

        jLabel42.setText("SI");
        jPanel9.add(jLabel42);

        jPanel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel51.setText("NO");
        jPanel15.add(jLabel51);
        jPanel15.add(btnOpcion1Pregunta15);
        jPanel15.add(btnOpcion2Pregunta15);

        jLabel52.setText("SI");
        jPanel15.add(jLabel52);

        jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel59.setText("NO");
        jPanel18.add(jLabel59);
        jPanel18.add(btnOpcion1Pregunta16);
        jPanel18.add(btnOpcion2Pregunta16);

        jLabel60.setText("SI");
        jPanel18.add(jLabel60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarTestActionPerformed
        // TODO add your handling code here:
        try {
            clips.reset();
            if (btnOpcion1Pregunta1.isSelected() == true) {
                Valorpregunta1 = 1;
            } else if (btnOpcion2Pregunta1.isSelected()) {
                Valorpregunta1 = 2;
            }

            if (btnOpcion1Pregunta2.isSelected() == true) {
                Valorpregunta2 = 1;
            } else if (btnOpcion2Pregunta2.isSelected()) {
                Valorpregunta2 = 2;
            }

            if (btnOpcion1Pregunta3.isSelected() == true) {
                Valorpregunta3 = 1;
            } else if (btnOpcion2Pregunta3.isSelected()) {
                Valorpregunta3 = 2;
            }

            if (btnOpcion1Pregunta4.isSelected() == true) {
                Valorpregunta4 = 1;
            } else if (btnOpcion2Pregunta4.isSelected()) {
                Valorpregunta4 = 2;
            }

            if (btnOpcion1Pregunta5.isSelected() == true) {
                Valorpregunta5 = 1;
            } else if (btnOpcion2Pregunta5.isSelected()) {
                Valorpregunta5 = 2;
            }

            if (btnOpcion1Pregunta6.isSelected() == true) {
                Valorpregunta6 = 1;
            } else if (btnOpcion2Pregunta5.isSelected()) {
                Valorpregunta6 = 2;
            }

            if (btnOpcion1Pregunta7.isSelected() == true) {
                Valorpregunta7 = 1;
            } else if (btnOpcion2Pregunta7.isSelected()) {
                Valorpregunta7 = 2;
            }

            if (btnOpcion1Pregunta8.isSelected() == true) {
                Valorpregunta8 = 1;
            } else if (btnOpcion2Pregunta8.isSelected()) {
                Valorpregunta8 = 2;
            }

            if (btnOpcion1Pregunta9.isSelected() == true) {
                Valorpregunta9 = 1;
            } else if (btnOpcion2Pregunta9.isSelected()) {
                Valorpregunta9 = 2;
            }

            if (btnOpcion1Pregunta10.isSelected() == true) {
                Valorpregunta10 = 1;
            } else if (btnOpcion2Pregunta10.isSelected()) {
                Valorpregunta10 = 2;
            }

            if (btnOpcion1Pregunta11.isSelected() == true) {
                Valorpregunta11 = 1;
            } else if (btnOpcion2Pregunta11.isSelected()) {
                Valorpregunta11 = 2;
            }
            if (btnOpcion1Pregunta12.isSelected() == true) {
                Valorpregunta12 = 1;
            } else if (btnOpcion2Pregunta12.isSelected()) {
                Valorpregunta12 = 2;
            }
            if (btnOpcion1Pregunta13.isSelected() == true) {
                Valorpregunta13 = 1;
            } else if (btnOpcion2Pregunta13.isSelected()) {
                Valorpregunta13 = 2;
            }
            if (btnOpcion1Pregunta14.isSelected() == true) {
                Valorpregunta14 = 1;
            } else if (btnOpcion2Pregunta14.isSelected()) {
                Valorpregunta14 = 2;
            }
            if (btnOpcion1Pregunta15.isSelected() == true) {
                Valorpregunta15 = 1;
            } else if (btnOpcion2Pregunta15.isSelected()) {
                Valorpregunta15 = 2;
            }
            if (btnOpcion1Pregunta16.isSelected() == true) {
                Valorpregunta16 = 1;
            } else if (btnOpcion2Pregunta16.isSelected()) {
                Valorpregunta16 = 2;
            }
            if (btnOpcion1Pregunta17.isSelected() == true) {
                Valorpregunta17 = 1;
            } else if (btnOpcion2Pregunta17.isSelected()) {
                Valorpregunta17 = 2;
            }
            if (btnOpcion1Pregunta18.isSelected() == true) {
                Valorpregunta18 = 1;
            } else if (btnOpcion2Pregunta18.isSelected()) {
                Valorpregunta18 = 2;
            }

            clips.eval("(assert (Test                    \n"
                    + "       (Pregunta1 " + Valorpregunta1 + ")\n"
                    + "    (Pregunta2 " + Valorpregunta2 + ")\n"
                    + "    (Pregunta3 " + Valorpregunta3 + ")\n"
                    + "    (Pregunta4 " + Valorpregunta4 + ")\n"
                    + "    (Pregunta5 " + Valorpregunta5 + ")\n"
                    + "    (Pregunta6 " + Valorpregunta6 + ")\n"
                    + "    (Pregunta7 " + Valorpregunta7 + ")\n"
                    + "    (Pregunta8 " + Valorpregunta8 + ")\n"
                    + "    (Pregunta9 " + Valorpregunta9 + ")\n"
                    + "    (Pregunta10 " + Valorpregunta10 + ")\n"
                    + "    (Pregunta11 " + Valorpregunta11 + ")\n"
                    + "    (Pregunta12 " + Valorpregunta12 + ")\n"
                    + "    (Pregunta13 " + Valorpregunta13 + ")\n"
                    + "    (Pregunta14 " + Valorpregunta14 + ")\n"
                    + "    (Pregunta15 " + Valorpregunta15 + ")\n"
                    + "    (Pregunta16 " + Valorpregunta16 + ")\n"
                    + "    (Pregunta17 " + Valorpregunta17 + ")\n"
                    + "    (Pregunta18 " + Valorpregunta18 + ")\n"
                    + "	)\n"
                    + ")");

            clips.run();
            String evaluar = "(find-all-facts ((?r ResultadoTest )) TRUE)";
            PrimitiveValue value = clips.eval(evaluar);
            String Respuesta = value.get(0).getFactSlot("respuesta").toString();

            String evaluar1 = "(find-all-facts ((?r ResultadoTest )) TRUE)";
            PrimitiveValue value1 = clips.eval(evaluar1);

            String Respuesta1 = value1.get(0).getFactSlot("puntaje").toString();

            JOptionPane.showMessageDialog(null, "La discapacidad Motriz es: " + Respuesta + " Puntaje: (" + Respuesta1 + ")");

        } catch (Exception ex) {
            ex.printStackTrace();
//Logger.getLogger(VentanaPersonalidad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRealizarTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnOpcion1Pregunta1;
    private javax.swing.JRadioButton btnOpcion1Pregunta10;
    private javax.swing.JRadioButton btnOpcion1Pregunta11;
    private javax.swing.JRadioButton btnOpcion1Pregunta12;
    private javax.swing.JRadioButton btnOpcion1Pregunta13;
    private javax.swing.JRadioButton btnOpcion1Pregunta14;
    private javax.swing.JRadioButton btnOpcion1Pregunta15;
    private javax.swing.JRadioButton btnOpcion1Pregunta16;
    private javax.swing.JRadioButton btnOpcion1Pregunta17;
    private javax.swing.JRadioButton btnOpcion1Pregunta18;
    private javax.swing.JRadioButton btnOpcion1Pregunta2;
    private javax.swing.JRadioButton btnOpcion1Pregunta3;
    private javax.swing.JRadioButton btnOpcion1Pregunta4;
    private javax.swing.JRadioButton btnOpcion1Pregunta5;
    private javax.swing.JRadioButton btnOpcion1Pregunta6;
    private javax.swing.JRadioButton btnOpcion1Pregunta7;
    private javax.swing.JRadioButton btnOpcion1Pregunta8;
    private javax.swing.JRadioButton btnOpcion1Pregunta9;
    private javax.swing.JRadioButton btnOpcion2Pregunta1;
    private javax.swing.JRadioButton btnOpcion2Pregunta10;
    private javax.swing.JRadioButton btnOpcion2Pregunta11;
    private javax.swing.JRadioButton btnOpcion2Pregunta12;
    private javax.swing.JRadioButton btnOpcion2Pregunta13;
    private javax.swing.JRadioButton btnOpcion2Pregunta14;
    private javax.swing.JRadioButton btnOpcion2Pregunta15;
    private javax.swing.JRadioButton btnOpcion2Pregunta16;
    private javax.swing.JRadioButton btnOpcion2Pregunta17;
    private javax.swing.JRadioButton btnOpcion2Pregunta18;
    private javax.swing.JRadioButton btnOpcion2Pregunta2;
    private javax.swing.JRadioButton btnOpcion2Pregunta3;
    private javax.swing.JRadioButton btnOpcion2Pregunta4;
    private javax.swing.JRadioButton btnOpcion2Pregunta5;
    private javax.swing.JRadioButton btnOpcion2Pregunta6;
    private javax.swing.JRadioButton btnOpcion2Pregunta7;
    private javax.swing.JRadioButton btnOpcion2Pregunta8;
    private javax.swing.JRadioButton btnOpcion2Pregunta9;
    private javax.swing.JButton btnRealizarTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
